2020-12-08 00:39:21,126 INFO: Microblog startup [in /Users/user/PycharmProjects/microblog/app/__init__.py:53]
2020-12-10 22:43:37,335 INFO: Microblog startup [in /Users/user/PycharmProjects/microblog/app/__init__.py:54]
2020-12-10 22:44:46,684 INFO: Microblog startup [in /Users/user/PycharmProjects/microblog/app/__init__.py:54]
2020-12-10 22:44:52,084 ERROR: Exception on /index [GET] [in /Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/user/PycharmProjects/microblog/app/routes.py", line 27, in index
    print(boo)
NameError: name 'boo' is not defined
2020-12-10 22:45:30,672 INFO: Microblog startup [in /Users/user/PycharmProjects/microblog/app/__init__.py:54]
2020-12-10 22:45:41,865 INFO: Microblog startup [in /Users/user/PycharmProjects/microblog/app/__init__.py:54]
2020-12-10 22:46:58,437 INFO: Microblog startup [in /Users/user/PycharmProjects/microblog/app/__init__.py:55]
2020-12-10 22:47:06,602 ERROR: Exception on /index [GET] [in /Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/PycharmProjects/venvs/microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/user/PycharmProjects/microblog/app/routes.py", line 27, in index
    print(boo)
NameError: name 'boo' is not defined
2020-12-10 22:49:04,171 INFO: Microblog startup [in /Users/user/PycharmProjects/microblog/app/__init__.py:53]
